Falling-Block: "ANVIL"
Landed-Crate: "CHEST"
Amount-Of-Items: 3
Rewards:
  1:
    chance: 70
    item: "DIAMOND"
    amount: 5
    name: "DIRT" #This item will run the command and not give the item.
    lore:
      - ""
      - "&7Special xmas diamond"
    enable-enchants: false
    enchants:
      - "DURABILITY:3"
    commands:
      - "give %player% glass 1"
  2:
    chance: 65
    item: "DIAMOND_SWORD"
    amount: 1
    name: "&c&lXMAS DIAMOND SWORD"
    lore:
      - ""
      - "&f&lSpecial xmas diamond sword"
    enable-enchants: true
    enchants:
      - "DURABILITY:3"
    commands:
      - "give %player% glass 1"
  3:
    chance: 90
    item: "DIAMOND_HELMET"
    amount: 1
    name: "&c&lXMAS DIAMOND HELMET"
    lore:
      - ""
      - "&f&lSpecial xmas diamond helmet"
    enable-enchants: true
    enchants:
      - "DURABILITY:3"
    commands:
      - "give %player% glass 1"
  4:
    chance: 25
    item: "DIAMOND_CHESTPLATE"
    amount: 1
    name: "&c&lXMAS DIAMOND CHESTPLATE"
    lore:
      - ""
      - "&f&lSpecial xmas diamond chestplate"
    enable-enchants: true
    enchants:
      - "DURABILITY:3"
    commands:
      - "give %player% glass 1"
  5:
    chance: 90
    item: "DIAMOND_BOOTS"
    amount: 1
    name: "&c&lXMAS DIAMOND BOOTS"
    lore:
      - ""
      - "&f&lSpecial xmas diamond helmet"
    enable-enchants: true
    enchants:
      - "DURABILITY:3"
    commands:
      - "give %player% stone 20"
  6:
    chance: 25
    item: "DIAMOND_LEGGINGS"
    amount: 1
    name: "&c&lXMAS DIAMOND LEGGINGS"
    lore:
      - ""
      - "&f&lSpecial xmas diamond chestplate"
    enable-enchants: true
    enchants:
      - "DURABILITY:3"
      - "PROTECTION_ENVIRONMENTAL:4"
    commands:
      - "give %player% glass 1"
  7:
    chance: 25
    item: "GOLDEN_APPLES"
    amount: 1
    name: "&6&lGolden Apples"
    lore:
      - ""
    enable-enchants: false
    enchants:
      - "DURABILITY:3"
    commands:
      - "give %player% glass 1"
